export type TabName =
    "Reconciliation"
    | "Revenue"
    | "Fees"
    | "Refund"
    | "Disputes"
    | "Returns"
    | "Accounting Systems"
    | "OMS"
    | "PSPs"
    | "Banks"
    | "Vendors"
    | "Payments"
    | "Customers"
    | "Invoices"
    | "Accounts Receivables"
    | "Accounts Payables"
    | "Balance Sheet"
    | "Profit & Loss"
