version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  cloudrun: circleci/gcp-cloud-run@1.0.0
  node: circleci/node@5.1.0
jobs:
#  build:
#    working_directory: ~/repo
#    docker:
#      - image: cimg/node:19.8.0
#    resource_class: small
#    steps:
#      - checkout
#      - run:
#          name: Update NPM
#          command: "sudo npm install -g npm@9.6.2"
#      - run:
#          name: Build Next.js app
#          command: npm run build
#      - restore_cache:
#          key: dependency-cache-{{ checksum "package-lock.json" }}
#      - save_cache:
#          key: dependency-cache-{{ checksum "package-lock.json" }}
#          paths:
#            - ./node_modules
#      - run:
#          name: Run tests
#          command: npm run test
  build_node_js:
    docker:
      - image: cimg/node:19.8.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@9.6.2"
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test
#  build_push_image_cloud_run_mangaged:
#    docker:
#      - image: google/cloud-sdk:latest
#    steps:
#      - checkout
#      - setup_remote_docker:
#          docker_layer_caching: false
#      - run:
#          name: Build app binary and Docker image
#          command: |
#            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV
#            echo ${GCP_PROJECT_KEY} | base64 --decode --ignore-garbage > $HOME/gcloud-service-key.json
#            echo 'export GOOGLE_CLOUD_KEYS=$(cat $HOME/gcloud-service-key.json)' >> $BASH_ENV
#            echo 'export TAG=${CIRCLE_SHA1}' >> $BASH_ENV
#            echo 'export IMAGE_NAME=$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV && source $BASH_ENV
#            sudo npm install -g npm@9.6.2
#            docker build -t us.gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME -t us.gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME:$TAG .
#      - gcp-gcr/gcr-auth:
#          gcloud-service-key: GOOGLE_CLOUD_KEYS
#          google-project-id: GOOGLE_PROJECT_ID
#          google-compute-zone: GOOGLE_COMPUTE_ZONE
#      - gcp-gcr/push-image:
#          google-project-id: GOOGLE_PROJECT_ID
#          registry-url: "us.gcr.io"
#          image: $IMAGE_NAME
#      - cloudrun/deploy:
#          platform: "managed"
#          image: "us.gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME"
#          service-name: "orb-gcp-cloud-run"
#          region: $GOOGLE_COMPUTE_ZONE
#          unauthenticated: true
workflows:
  build_test_deploy:
    jobs:
      - build_node_js
      # - build_push_image_cloud_run_mangaged:
      #     requires:
      #       - build
